#!/usr/bin/env python2
import sys
import json
import re

def chunk(s, length=50):
   for i in range(0, len(s), length):
      yield s[i:length+i]

varName = sys.argv[1] if len(sys.argv)>1 else 'str'
first = True
for s in chunk(sys.stdin.read()):
    s = re.sub('}$', '', json.dumps({'s':s}).split(':')[1])
    if first:
        print 'String '+varName+' = '+ s +';'
        first = False
    else:
       print varName + ' += ' + s +';'

