#!/usr/bin/env bash
set -e
tomcat_version=$(curl -s http://apache.crihan.fr/dist/tomcat/tomcat-8/ | grep v8 | perl -pe "s/^.*v(8[^\\/]+).*$/\\1/"|sort|tail -1)
echo 'tomcat version : ' $tomcat_version

#tomcat_version=7.0.77
#tomcat_version=6.0.53

tomcat_major=$(echo $tomcat_version|sed -e 's/^\([0-9]\).*$/\1/')
tmpdir=/tmp/runwar
tomcatdir=${tmpdir}/apache-tomcat-${tomcat_version}
if [ ! -d ${tomcatdir} ]; then
    mkdir -p ${tmpdir}
    pushd ${tmpdir} >/dev/null
    wget http://apache.crihan.fr/dist/tomcat/tomcat-${tomcat_major}/v${tomcat_version}/bin/apache-tomcat-${tomcat_version}.tar.gz
    tar -zxf apache-tomcat-${tomcat_version}.tar.gz
    rm apache-tomcat-${tomcat_version}.tar.gz
    popd >/dev/null
fi
if [ -f "$1" ]; then
    deployed=$(readlink -m $1)
    path=$(basename $deployed | sed -e s/\.war$//)
    echo $deployed
    rm -rf $(find ${tomcatdir}/webapps -mindepth 1 -maxdepth 1)
    ln -s ${deployed} ${tomcatdir}/webapps/$(basename $deployed)
    xdg-open 'http://localhost:8080/'$path
    ${tomcatdir}/bin/catalina.sh run
elif [ -d "$1" ]; then
    path=$(basename $(readlink -m $1))
    echo $path
    rm -f "${tomcatdir}/webapps/${path}" 2>/dev/null
    ln -s $(readlink -m $1) "${tomcatdir}/webapps/${path}"
    xdg-open 'http://localhost:8080/'$path
    ${tomcatdir}/bin/catalina.sh run
else
   echo "usage : $0 <war file or directory>" >&2
   exit 1
fi

